services:
  # nginx:
  #   image: nginx:alpine
  #   container_name: store_nginx
  #   depends_on:
  #     - order-service
  #     - postgres
  #   ports:
  #     - "3333:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro

  # order-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   expose:
  #     - "3333"
  #   depends_on:
  #     - postgres
  #   restart: always
  #   volumes:
  #     - ./config/config.docker.yaml:/app/config/config.yaml
  #   command: ["./order-service", "http-serve"]
  #   deploy:
  #     replicas: 1 

  postgres:
    image: postgres:latest
    container_name: store_postgres
    environment:
      POSTGRES_USER: dborder
      POSTGRES_PASSWORD: SecretP@ssw0rd
      POSTGRES_DB: store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  postgres_data: