
HttpServer:
  Port: 3333

Database:
  Username: dborder
  Password: SecretP@ssw0rd
  Host: localhost
  Port: 5432
  DatabaseName: store
  DatabaseSchema: store

Logger:
  level: debug
  format: compact  # json or compact
  add_source: true
  time_format: "2006-01-02T15:04:05.000Z"
  output: stdout  # stdout, stderr, or file path
  enable_color: true  # Enable colored output for compact format
