
HttpServer:
  Port: 3333

Database:
  Username: dborder
  Password: SecretP@ssw0rd
  Host: localhost
  Port: 5432
  DatabaseName: store
  DatabaseSchema: store

Logger:
  Level: debug
  Format: compact
  Output: stdout
  AddSource: true
  EnableColor: false
  EnableFile: false
  FilePath: ./logs/dev.log  # File path (not used when EnableFile is false)