
HttpServer:
  Port: 3333

Database:
  Username: dborder
  Password: SecretP@ssw0rd
  Host: postgres
  Port: 5432
  DatabaseName: store
  DatabaseSchema: store

Logger:
  Level: info
  Format: json
  AddSource: true
  Output: stdout # Docker can collect these logs