
HttpServer:
  Port: 3333

Database:
  Username: dborder
  Password: SecretP@ssw0rd
  Host: localhost
  Port: 5432
  DatabaseName: store
  DatabaseSchema: store

Logger:
  Format: compact     # ✅ For colored output
  Level: debug
  AddSource: true
  Output: stdout      # ✅ Console output
  EnableColor: true   # ✅ Enable colors
  EnableFile: false   # ✅ Disable file logging for development
  FilePath: ./logs/dev.log