
HttpServer:
  Port: 3333

Database:
  Username: dborder
  Password: SecretP@ssw0rd
  Host: localhost
  Port: 5432
  DatabaseName: store
  DatabaseSchema: store

Logger:
  Format: compact
  Level: info
  AddSource: true
  Output: /log/app.log # Docker can collect these logs
  EnableColor: true  # Enable colored output for compact format