
HttpServer:
  Port: 3333

Database:
  Username: dborder
  Password: SecretP@ssw0rd
  Host: localhost
  Port: 5432
  DatabaseName: store
  DatabaseSchema: store

Logger:
  Level: debug
  Format: compact  # json or compact
  AddSource: true
  TimeFormat: "2006-01-02T15:04:05.000Z"
  Output: stdout  # stdout, stderr, or file path
  EnableColor: true  # Enable colored output for compact format
