HttpServer:
  Port: 3333
  RequestTimeout: 30s      # Default request timeout
  ServerTimeout: 60s       # Server read/write timeout
  IdleTimeout: 120s        # Connection idle timeout
  ShutdownTimeout: 30s     # Graceful shutdown timeout

Database:
  Username: dborder
  Password: SecretP@ssw0rd
  Host: postgres
  Port: 5432
  DatabaseName: store
  DatabaseSchema: store

Logger:
  Format: json
  Level: info        # More verbose for development
  AddSource: true
  Output: stdout      # Output to console for development
  EnableColor: true   # Enable colored output for compact format
  EnableFile: false   # Disable file logging for development